name: med
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dartz: ^0.10.1
  equatable: ^2.0.7

  # -------- FIREBASE (Compatible versions) ----------
  firebase_core: ^3.5.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.1.3
  firebase_auth: ^5.3.0

  # Other
  get_it: ^7.7.0
  flutter_bloc: ^8.1.4
  connectivity_plus: ^7.0.0
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  # replaces deprecated data_connection_checker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
